name: Build and deploy game

on:
  push:
    branches: [master]

env:
  GAME_NAME: tinywar

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Build release exe
        run: make build-release

      - name: Copy files to output folder
        shell: bash
        run: |
          mkdir -p output
          cp -r assets output/assets
          cp target/release/${{ env.GAME_NAME }}.exe output/
          cd output
          7z a ../${{ env.GAME_NAME }}-windows.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}-windows
          path: ${{ env.GAME_NAME }}-windows.zip

  # Separate job since butler only works on linux and we need
  # to run cargo build on windows to generate the .exe
  deploy-windows:
    runs-on: ubuntu-latest
    needs: build-windows

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}-zip
          path: .

      - name: Deploy to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ env.GAME_NAME }}
          ITCH_USER: tvdboom
          PACKAGE: ${{ env.GAME_NAME }}.zip

  build-deploy-wasm:
    name: Build WASM
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: hecrj/setup-rust-action@v2.0.1
        with:
          rust-version: stable

      - name: Build WASM
        run: make build-wasm

      - name: Copy assets
        run: cp -r $GITHUB_WORKSPACE/assets/ docs/assets

      - uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: docs/

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5

      - name: Deploy to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          ITCH_USER: tvdboom
          ITCH_GAME: ${{ env.GAME_NAME }}
          CHANNEL: html
          PACKAGE: docs/
